### PR TITLE
Monthfix -- This program wasnt working for a month :D

### PR DESCRIPTION
**Pull request by mtib**
I just looked at it because I thought of updating it via curl to find it not working.
It was a quick fix.

This PR contains some other stuff I did encapsulation the main stuff in a main method, which makes it theoretically possible to import the functions, idk when you would want to do that, but it's possible.

### CODE REVIEW

**Comment by mtib** [comment]
Also the badge wasn't working, and I fixed that link

**Comment by waseem18** [comment]
Hello @mtib 

Thank you so much. I wasn't focussing much on 'Hacks' actually. 
For a couple of days, I can't access a computer. So I can't test the code. As the travis tests have also passed, I'm planning to merge this.

What do you say?
Thanks again! Your contribution is what making this project up to date. :+1:

**Comment by mtib** [comment]
Merging this should be a no-brainer.

**Comment by waseem18** [comment]
:+1:

**Pull request merged**
